/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./react-app/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#0c1427",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "primary-container": "#21283c",
        "outline": "#75777d",
        "on-primary-fixed": "#131b2e",
        "secondary": "#006c49",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-variant": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-container": "#888fa7",
        "secondary-fixed": "#6ffbbe",
        "inverse-on-surface": "#eaf1ff",
        "on-error": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-secondary-container": "#00714d",
        "inverse-surface": "#213145",
        "tertiary-container": "#3c2300",
        "surface-tint": "#565e74",
        "error-container": "#ffdad6",
        "secondary-container": "#6cf8bb",
        "on-background": "#0b1c30",
        "secondary-fixed-dim": "#4edea3",
        "outline-variant": "#c5c6cd",
        "on-tertiary-container": "#c88000",
        "on-surface-variant": "#45474c",
        "surface-bright": "#f8f9ff",
        "on-error-container": "#93000a",
        "tertiary": "#201100",
        "tertiary-fixed": "#ffddb8",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed-variant": "#3f465c",
        "on-surface": "#0b1c30",
        "inverse-primary": "#bec6e0",
        "on-secondary-fixed": "#002113",
        "surface-container": "#e5eeff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#2a1700",
        "error": "#ba1a1a",
        "surface-container-highest": "#d3e4fe",
        "background": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "surface": "#f8f9ff",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
