import { useReducer, useContext, ReactNode } from "react";
import CasesContext from "./casesContext";
import AppReducer from "../AppReducer";
import InViewContext from "../../context/inView/inViewContext";

import { toast } from "react-toastify";
import { get, post, put, del } from "../../utils/fetch";
import { GET_CASES } from "../types";
import type { CasesState as CasesStateType, InViewContextType, Case } from "../types";

interface CasesStateProps {
  children: ReactNode;
}

export default function CasesState({ children }: CasesStateProps) {
  const inViewContext = useContext(InViewContext) as InViewContextType;
  const currentUserInDisplay = inViewContext.state.userId;

  const initialState: CasesStateType = {
    user: "",
    cases: [],
    loadingCases: false,
  };
  const [state, dispatch] = useReducer(AppReducer, initialState);
  const apiUrlCases = `${data.root_url}/wp-json/${data.api_url}/cases`;

  const getCases = async (id: string | number, onlyFetch: boolean): Promise<Case[] | void> => {
    try {
      if (!onlyFetch) {
        dispatch({
          type: GET_CASES,
          payload: {
            user: state.user,
            cases: state.cases,
            loadingCases: true,
          },
        });
      }

      const res = await get(`${apiUrlCases}/${id}`, {
        headers: {
          "X-WP-Nonce": data.nonce,
        },
      });

      if (!onlyFetch) {
        dispatch({
          type: GET_CASES,
          payload: {
            user: state.user,
            cases: res.data,
            loadingCases: false,
          },
        });
      }

      return res.data;
    } catch (error) {
      console.log(error);
    }
  };

  const postCase = async (id: string | number, title: string): Promise<void> => {
    if (title === "") {
      alert("The title can not be blank!");
      return;
    }

    const dataToPost = { id_user: id, title: title };

    try {
      await post(`${apiUrlCases}/${id}`, dataToPost, {
        headers: {
          "X-WP-Nonce": data.nonce,
          "Content-type": "application/json",
        },
      });

      const getAllCases = await getCases(id, true);
      const casesArray = Array.isArray(getAllCases) ? getAllCases : [];
      const newCaseAutoGeneratedId = casesArray[casesArray.length - 1]?.id;
      const newCase = {
        id: newCaseAutoGeneratedId,
        id_user: id,
        title: title,
        status: "open",
      };
      const currentCases = state.cases;
      const newCases = [...currentCases, newCase];

      dispatch({
        type: GET_CASES,
        payload: {
          user: id,
          cases: newCases,
          loadingCases: false,
        },
      });

      toast.success(data.toast_case_added);
    } catch (error) {
      alert(data.alert_error_base + error);
    }
  };

  const toggleCase = async (id: string | number): Promise<void> => {
    try {
      await post(`${apiUrlCases}-status/${id}`, null, {
        headers: {
          "X-WP-Nonce": data.nonce,
        },
      });

      const currentCases = state.cases;
      const newCases = currentCases.map((theCase: Case) => {
        if (theCase.id.toString() === id.toString()) {
          return { ...theCase, status: theCase.status === "open" ? "close" : "open" };
        }
        return theCase;
      });

      dispatch({
        type: GET_CASES,
        payload: {
          user: state.user,
          cases: newCases,
          loadingCases: false,
        },
      });

      toast.success(data.toast_case_toggled);
    } catch (error) {
      alert(data.alert_error_base + error);
    }
  };

  const deleteCase = async (id: string | number, title: string): Promise<void> => {
    if (!confirm(`Are you sure you want to delete the case: ${title}?`)) return;

    try {
      await del(`${apiUrlCases}/${id}`, {
        headers: {
          "X-WP-Nonce": data.nonce,
        },
      });

      const currentCases = state.cases;
      const newCases = currentCases.filter(
        (theCase: Case) => theCase.id.toString() !== id.toString()
      );

      dispatch({
        type: GET_CASES,
        payload: {
          user: state.user,
          cases: newCases,
          loadingCases: false,
        },
      });

      toast.success(data.toast_case_deleted);
    } catch (error) {
      alert(data.alert_error_base + error);
    }
  };

  const editCase = async (id: string | number, id_user: string | number, newTitle: string): Promise<void> => {
    if (newTitle === "") {
      alert(data.alert_blank_case_title);
      return;
    }

    const idTitleObj = { id_user, title: newTitle };

    try {
      await put(`${apiUrlCases}/${id}`, idTitleObj, {
        headers: {
          "X-WP-Nonce": data.nonce,
          "Content-type": "application/json",
        },
      });

      const currentCases = state.cases;
      const newCases = currentCases.map((theCase: Case) => {
        if (theCase.id.toString() === id.toString()) {
          return { ...theCase, title: newTitle };
        }
        return theCase;
      });

      dispatch({
        type: GET_CASES,
        payload: {
          user: id_user,
          cases: newCases,
          loadingCases: false,
        },
      });

      toast.success(data.toast_case_edited);
    } catch (error) {
      alert(data.alert_error_base + error);
    }
  };

  return (
    <CasesContext.Provider
      value={{
        state,
        getCases,
        postCase,
        toggleCase,
        deleteCase,
        editCase,
        currentUserInDisplay,
        navigate: inViewContext.navigate,
      }}
    >
      {children}
    </CasesContext.Provider>
  );
}
