import { create } from "zustand";
import { get as fetchGet, post, put, del } from "../utils/fetch";
import { toast } from "react-toastify";
import type { Case } from "../types";

declare const data: Record<string, any>;

export interface CasesState {
  user: string | number;
  cases: Case[];
  loadingCases: boolean;
}

export interface CasesActions {
  getCases: (id: string | number, onlyFetch: boolean) => Promise<Case[] | void>;
  postCase: (id: string | number, title: string, extraData?: Record<string, any>) => Promise<void>;
  toggleCase: (id: string | number) => Promise<void>;
  deleteCase: (id: string | number, title: string) => Promise<void>;
  editCase: (
    id: string | number,
    id_user: string | number,
    newTitle: string,
    start_at?: string | null,
    due_at?: string | null,
  ) => Promise<void>;
}

export interface CasesStore extends CasesState, CasesActions {}

export const useCasesStore = create<CasesStore>((set, get) => {
  const apiUrlCases = `${data.root_url}/wp-json/${data.api_url}/cases`;

  return {
    user: "",
    cases: [],
    loadingCases: false,
    getCases: async (id: string | number, onlyFetch: boolean): Promise<Case[] | void> => {
      try {
        if (!onlyFetch) {
          set({ loadingCases: true });
        }

        const res = await fetchGet(`${apiUrlCases}/${id}`, {
          headers: { "X-WP-Nonce": data.nonce },
        });

        if (!onlyFetch) {
          set({ user: id, cases: res.data, loadingCases: false });
        }

        return res.data;
      } catch (error) {
        console.error("Error fetching cases:", error);
        if (!onlyFetch) {
          set({ loadingCases: false });
        }
      }
    },
    postCase: async (id: string | number, title: string, extraData?: Record<string, any>): Promise<void> => {
      if (title === "") {
        alert("The title can not be blank!");
        return;
      }

      const dataToPost: Record<string, any> = { id_user: id, title: title };
      if (extraData) {
        if (extraData.status) dataToPost.status = extraData.status;
        if (extraData.description) dataToPost.description = extraData.description;
        if (extraData.start_at) dataToPost.start_at = extraData.start_at;
        if (extraData.due_at) dataToPost.due_at = extraData.due_at;
      }

      try {
        await post(`${apiUrlCases}/${id}`, dataToPost, {
          headers: {
            "X-WP-Nonce": data.nonce,
            "Content-type": "application/json",
          },
        });

        const getAllCases = await get().getCases(id, true);
        const casesArray = Array.isArray(getAllCases) ? getAllCases : [];
        const newCaseAutoGeneratedId = casesArray[casesArray.length - 1]?.id;
        const newCase = {
          id: newCaseAutoGeneratedId,
          id_user: id,
          title: title,
          status: extraData?.status || "open",
          description: extraData?.description || "",
          start_at: extraData?.start_at || null,
          due_at: extraData?.due_at || null,
          created_at: new Date().toISOString(),
        };
        const currentCases = get().cases;
        const newCases = [...currentCases, newCase];

        set({ user: id, cases: newCases, loadingCases: false });

        toast.success(data.toast_case_added, {
          position: "bottom-right",
          autoClose: 5000,
          hideProgressBar: true,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
        });
      } catch (error) {
        alert(data.alert_error_base + error);
      }
    },
    toggleCase: async (id: string | number): Promise<void> => {
      try {
        await post(`${apiUrlCases}-status/${id}`, null, {
          headers: { "X-WP-Nonce": data.nonce },
        });

        const currentCases = get().cases;
        const newCases = currentCases.map((theCase: Case) => {
          if (theCase.id.toString() === id.toString()) {
            return { ...theCase, status: theCase.status === "open" ? "close" : "open" };
          }
          return theCase;
        });

        set({ cases: newCases });

        toast.success(data.toast_case_toggled, {
          position: "bottom-right",
          autoClose: 5000,
          hideProgressBar: true,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
        });
      } catch (error) {
        alert(data.alert_error_base + error);
      }
    },
    deleteCase: async (id: string | number, title: string): Promise<void> => {
      if (!confirm(`Are you sure you want to delete the case: ${title}?`)) return;

      try {
        await del(`${apiUrlCases}/${id}`, {
          headers: { "X-WP-Nonce": data.nonce },
        });

        const currentCases = get().cases;
        const newCases = currentCases.filter(
          (theCase: Case) => theCase.id.toString() !== id.toString()
        );

        set({ cases: newCases });

        toast.success(data.toast_case_deleted, {
          position: "bottom-right",
          autoClose: 5000,
          hideProgressBar: true,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
        });
      } catch (error) {
        alert(data.alert_error_base + error);
      }
    },
    editCase: async (
      id: string | number,
      id_user: string | number,
      newTitle: string,
      start_at?: string | null,
      due_at?: string | null,
    ): Promise<void> => {
      if (newTitle === "") {
        alert(data.alert_error_base + data.alert_blank_case_title);
        return;
      }

      const idTitleObj: Record<string, any> = { id_user, title: newTitle };
      if (start_at !== undefined) idTitleObj.start_at = start_at;
      if (due_at !== undefined) idTitleObj.due_at = due_at;

      try {
        await put(`${apiUrlCases}/${id}`, idTitleObj, {
          headers: {
            "X-WP-Nonce": data.nonce,
            "Content-type": "application/json",
          },
        });

        const currentCases = get().cases;
        const newCases = currentCases.map((theCase: Case) => {
          if (theCase.id.toString() === id.toString()) {
            const updated: Case = { ...theCase, title: newTitle };
            if (start_at !== undefined) updated.start_at = start_at;
            if (due_at !== undefined) updated.due_at = due_at;
            return updated;
          }
          return theCase;
        });

        set({ user: id_user, cases: newCases });

        toast.success(data.toast_case_edited, {
          position: "bottom-right",
          autoClose: 5000,
          hideProgressBar: true,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
        });
      } catch (error) {
        alert(data.alert_error_base + error);
      }
    },
  };
});
