name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*"

jobs:
  svn-deploy:
    uses: ./.github/workflows/svn-deploy.yml
    with:
      ref: stolmc
      slug: service-tracker-stolmc
    secrets:
      SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
      SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
